- name: Setup Firewall Rules
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - 53/udp
    - 53/tcp
    - 67/udp
    - 69/udp
    - 80/tcp
    - 443/tcp
    - 5000/tcp
    - 5647/tcp
    - 8000/tcp
    - 8140/tcp
    - 8443/tcp
    - 9090/tcp
